version: '3.8'

services:
  agente-ti-alesc:
    build: .
    image: agente-ti-alesc:latest
    container_name: agente_ia_prod
    ports:
      - "8501:8501"
    env_file:
      - .env
    volumes:
      - ./data:/app/data  # Mapeia a pasta local data para o container
    shm_size: '2gb'       # OBRIGATÓRIO para o FAISS (processamento vetorial)
    deploy:
      resources:
        limits:
          memory: 2G
    restart: always
    # Adicionando o comando explícito para garantir os parâmetros do Streamlit
    command: streamlit run app.py --server.port=8501 --server.address=0.0.0.0 --server.maxMessageSize=200